### ISSUE TITLE
文讀，白話相反

### ISSUE THREAD

**Issue by hansioux** [baconbao/TaiwaneseWizard#1]
感謝創作這支工具。

我發現目前在 option 選單中選文讀台，和白話台的時候，讀出來的結果是相反的。不論 firefox 或是 chrome 的版本都有這個錯誤。

例句： 
教育部日前說尷尬要讀成兼介之我見

如果把選項設成文讀台，台語兒唸出的結果是：
kàu-io̍k-pōo jit-tsîng suè kam-kài ài tha̍k siânn kiām-kài tsi guá-kìnn

其中 說=suè 要=ài 讀=tha̍k 成=siânn 我=guá 見=kìnn 全部都是白話音，而不是文讀音。

如果把選項設成白話台，台語兒唸出的結果是：
kàu-io̍k-pōo jit-tsîng suat kam-kài iàu tho̍k sîng kiām-kài tsi ngóo-kiàn

其中 說=suat 要=iàu 讀=tho̍k 成=sîng 我=ngóo 見=kiàn 全部都是文讀音，而不是白話音。

也就是說在 options.html  裡面雖然設成下面這樣，但最後結果仍是相反的。

&lt;input id="v0a" type="radio" name="voiceStyle" value="TW_LIT_AKoan" /> <label>文讀台</label>
&lt;input id="v0b" type="radio" name="voiceStyle" value="TW_SPK_AKoan" /> <label>白話台</label>

我本來以為 SPK 和 LIT 互調應該是從 tts 那邊就錯了，奇怪的是我去 tts.itri.org.tw 試的時候卻是正確的。因此應該還是台語兒哪裡 coding 出了錯。

無法幫你修正，不過希望提供足夠的資訊幫助你找出bug在哪。

**Comment by baconbao** [comment]
感謝您的通知。

Chrome版本已經修正完成並且應該可以更新了。
Firefox版本也已經修正完成並送交審核，依慣例會有一段等待時間，最長可能會到一個月。

至於原因方面，我是按照工研院TTS API指南設定的： http://tts.itri.org.tw/development/web_service_api.php
比對後發現無誤，因此推測應該是工研院的API指南那邊寫反了，這點我會協助在日後通知他們。

再次感謝您的通知，很有幫助，謝謝！ :smile:

**Comment by baconbao** [comment]
Firefox的審核已經在剛剛通過囉，歡迎使用 :smiley: 並再次感謝您的通知。
